# Generated by Django 5.1.4 on 2024-12-20 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, default='Unknown author', max_length=100)),
                ('Pages', models.IntegerField(default=0)),
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('language', models.CharField(choices=[('English', 'English'), ('Korean', 'Korean'), ('Bahasa', 'Bahasa'), ('Spanish', 'Spanish'), ('Other', 'Other')], default='Other', max_length=20)),
            ],
        ),
    ]
