# Generated by Django 5.1.4 on 2024-12-21 15:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore_App', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Adventure', 'Adventure'), ('Sci-Fi', 'Sci-Fi'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Historical Fiction', 'Historical Fiction'), ('Horror', 'Horror'), ('Literary', 'Literary'), ('Young Adult', 'Young Adult'), ('Non-Fiction', 'Non-Fiction'), ('Biography', 'Biography'), ('History', 'History'), ('Science', 'Science'), ('Travel', 'Travel'), ('Cookbook', 'Cookbook'), ('Philosophy', 'Philosophy'), ('Art', 'Art'), ('Graphic Novel', 'Graphic Novel'), ('Poetry', 'Poetry'), ('Anthology', 'Anthology'), ('Fiction', 'Fiction')], max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Pages',
            new_name='pages',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(blank=True, default='No Synopsis'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(choices=[('English', 'English'), ('Korean', 'Korean'), ('Bahasa', 'Bahasa'), ('Spanish', 'Spanish'), ('Other', 'Other')], default='English', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='Bookstore_App.genre'),
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='preferred_customers', to='Bookstore_App.genre'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('book_quantity', models.PositiveIntegerField(default=1)),
                ('total_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Bookstore_App.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Bookstore_App.customer')),
            ],
        ),
    ]
